### PR TITLE
Update readme to highlight alpha status

### PR DESCRIPTION
**Pull request by mrjackdavis**

### CODE REVIEW

**Comment by mrjackdavis** [comment]
@Dermah do you want to rename this project `fossilize-aws-ebs` as per #3 ?

**Comment by Dermah** [comment]
I think if we do that here then we will also need to update the docs and all uses of `backups:config-v0` to something more like `fossilize:config-v0`, among other things

**Comment by mrjackdavis** [comment]
@Dermah do you want to do it here? Up to you

**Comment by Dermah** [comment]
I'll do it here after #39 is finalised since that has some strings that will be affected.

**Comment by Dermah** [comment]
Approved. Nevermind, we'll do it live

**Pull request merged**
