### PR TITLE
More thorough tests for EC2Store

### PR DESCRIPTION
**Pull request by Dermah**
Here come some tests that break everything!

Also:

- `npm run watch` task (looks really cool in the terminal)
- Added a fixtures file to store EC2 mock responses sorta out of the way

Todo:
- [x] Simplify the object returned by EC2 Store
- [x] Write tests for EC2 store as demo
- [x] ~~Parser for backup tag~~

### CODE REVIEW

**Comment by mrjackdavis** [comment]
@Dermah do you want to merge this to master? Or leave it as a pickup point for contributors?

**Comment by Dermah** [comment]
I'll merge to master with the failing tests skipped as they were before.

**Comment by Dermah** [comment]
I need convincing that we need a seperate parser for tags. EC2Store maps the entire response object along with its tags and this feels ok at the moment. Tags are parsed differently according to what kind of EC2 object they are on.

**Comment by Dermah** [comment]
Added instructions to #6 and #7 detailing how to get started with the tests written here

**Comment by mrjackdavis** [comment]
Approved! LGTM

**Pull request merged**
